### ISSUE TITLE
How can I fix this ?

### ISSUE THREAD

**Issue by kthenurseone** [marusinm/eth-wallet#30]
![image](https://user-images.githubusercontent.com/54042275/161291176-b2a1390e-fdc3-4b46-a4fc-9da62cf8c564.png)

**Comment by kthenurseone** [comment]
C:\Users\Kerim\Downloads\eth-wallet-master\eth-wallet-master>pip install .
Processing c:\users\kerim\downloads\eth-wallet-master\eth-wallet-master
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      C:\Users\Kerim\AppData\Roaming\Python\Python310\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Kerim\Downloads\eth-wallet-master\eth-wallet-master\setup.py", line 4, in <module>
          setup(use_scm_version=True)
        File "C:\Users\Kerim\AppData\Roaming\Python\Python310\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\distutils\core.py", line 108, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\Kerim\AppData\Roaming\Python\Python310\site-packages\setuptools\dist.py", line 453, in __init__
          _Distribution.__init__(
        File "C:\Users\Kerim\AppData\Local\Programs\Python\Python310\lib\distutils\dist.py", line 292, in __init__
          self.finalize_options()
        File "C:\Users\Kerim\AppData\Roaming\Python\Python310\site-packages\setuptools\dist.py", line 831, in finalize_options
          ep(self)
        File "C:\Users\Kerim\AppData\Roaming\Python\Python310\site-packages\setuptools\dist.py", line 852, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "c:\users\kerim\downloads\eth-wallet-master\eth-wallet-master\.eggs\setuptools_scm-6.4.2-py3.10.egg\setuptools_scm\integration.py", line 75, in version_keyword
          _assign_version(dist, config)
        File "c:\users\kerim\downloads\eth-wallet-master\eth-wallet-master\.eggs\setuptools_scm-6.4.2-py3.10.egg\setuptools_scm\integration.py", line 51, in _assign_version
          _version_missing(config)
        File "c:\users\kerim\downloads\eth-wallet-master\eth-wallet-master\.eggs\setuptools_scm-6.4.2-py3.10.egg\setuptools_scm\__init__.py", line 106, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for C:\Users\Kerim\Downloads\eth-wallet-master\eth-wallet-master.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
